windows_task:
    windows_container:
        os_version: 1709
        dockerfile: CI/Windows/Dockerfile

    build_script:
        - mkdir build
        - cd build
        - call "C:\Program Files (x86)\Microsoft Visual Studio 15.0\VC\vcvarsall.bat"
        - cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=Debug ..
        - msbuild synergy-core.sln /p:Platform="x64" /p:Configuration=Debug /m
