windows_task:
    timeout_in: 90m
    windows_container:
        os_version: 2019
        dockerfile: CI/Windows/Dockerfile

    build_script:
        - mkdir build
        - cd build
        - cmake -DCMAKE_BUILD_TYPE=Debug ..
        - msbuild synergy-core.sln /p:Platform="x64" /p:Configuration=Debug /m
