windows_task:
    windows_container:
        image: cirrusci/windowsservercore:1709
        os_version: 1709

    build_script:
        - mkdir build
        - cd build
        - cmake -DCMAKE_BUILD_TYPE=Debug ..
        - msbuild synergy-core.sln /p:Platform="x64" /p:Configuration=Debug /m
