trigger:
- master

jobs: 
- job: Windows
  strategy:
    matrix:
      vs2019:
        image: windows-2019

  pool: 
    vmImage: $[ variables['image'] ]

  - script: |
     $client = new-object System.Net.WebClient
     $client.DownloadFile("http://download.qt.io/official_releases/qt/5.9/5.9.9/qt-opensource-windows-x86-5.9.9.exe","C:\tmp\qt-opensource-windows.exe")
     C:\tmp\qt-opensource-windows.exe --script qt-installer-noninteractive.qt
    displayName: 'Install QT 5.9.9'

  - script: |
      mkdir build
      cd build
      cmake -G "Visual Studio 16 2019 Win64" -DCMAKE_BUILD_TYPE=Release ..
      msbuild synergy-core.sln /p:Platform="x64" /p:Configuration=Release /m
    displayName: 'Build x64'
  
  - script: |
      mkdir build
      cd build
      cmake -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Release ..
      msbuild synergy-core.sln /p:Platform="x86" /p:Configuration=Release /m
    displayName: 'Build x86'