trigger:
- master

jobs: 
- job: LinuxDeb
  pool: 
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      ubuntu16:
        image: symless/ubuntu-sudo:16.04
      ubuntu18:
        image: symless/ubuntu-sudo:18.04
      ubuntu19:
        image: symless/ubuntu-sudo:19.04
      debian9:
        image: symless/debian-sudo:stretch

  container: $[ variables['image'] ]

  steps:
  - script: |
      sudo ln -snf /usr/share/zoneinfo/Europe/London /etc/localtime
      sudo bash -c "echo 'Europe/London' > /etc/timezone"
    displayName: 'Sort out timezones for updates'

  - script: |
      sudo DEBIAN_FRONTEND=noninteractive 
      sudo apt-get -y update
      sudo apt-get -y upgrade
      sudo apt-get -y install git cmake qtbase5-dev build-essential libx11-dev libxtst-dev libgl1-mesa-dev libssl-dev libavahi-compat-libdnssd-dev debhelper devscripts
      sudo apt-get -y install qttools5-dev qttools5-dev-tools --no-install-recommends #These will try to install gnome if we allow dependancies
    displayName: 'Install Pakages'

  - script: |
      mkdir build
      cd build
      cmake ..
      make
    displayName: 'Build'
