trigger:
- master

jobs: 
- job: LinuxRHEL
  pool: 
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      centos7:
        image: symless/centos-sudo:7

  container: $[ variables['image'] ]

  steps:
  - script: |
      sudo yum -y update
      sudo yum -y install epel-release cmake3 boost-static git libXtst-devel qt5-qtbase-devel qt5-qtdeclarative-devel libcurl-devel openssl-devel avahi-compat-libdns_sd-devel autoconf automake gcc gcc-c++ make rpm-build redhat-rpm-config rpm-sign
    displayName: 'Install Pakages'
    
  - script: |
      mkdir build
      cd build
      cmake3 ..
      make
    displayName: 'Build'

  