trigger:
- master

jobs: 
- job: Windows
  strategy:
    matrix:
      vs2019:
        image: windows-2019

  pool: 
    vmImage: $[ variables['image'] ]



  steps:
#As the official installer is rather 'slow' use an unofficial installer QLI
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        New-Item -Force -ItemType Directory -Path ".\deps\"
        $client = new-object System.Net.WebClient
        $client.DownloadFile("https://github.com/nelsonjchen/qli-installer/archive/v2019.05.26.1.zip","deps\qli.zip")
    displayName: 'Downloading QLI'
  - task: ExtractFiles@1
    inputs:
      archiveFilePatterns: './deps/*.zip'
      destinationFolder: './deps/'
      cleanDestinationFolder: false
    displayName: 'Extracting QLI'

  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: 'pip install -r .\deps\qli\requirements.txt'
    displayName: 'Install QLI requirements'
- task: PythonScript@0
  inputs:
    scriptSource: 'filePath'
    scriptPath: '.\deps\qli\qli-installer.py'
    arguments: '5.9.5 windows desktop win32_msvc2017 win64_msvc2017_64'

  - script: |
      mkdir build
      cd build
      cmake -G "Visual Studio 16 2019 Win64" -DCMAKE_BUILD_TYPE=Release ..
      msbuild synergy-core.sln /p:Platform="x64" /p:Configuration=Release /m
    displayName: 'Build x64'
  
  - script: |
      mkdir build
      cd build
      cmake -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Release ..
      msbuild synergy-core.sln /p:Platform="x86" /p:Configuration=Release /m
    displayName: 'Build x86'