trigger:
- master

jobs: 
- job: Linux
  pool: 
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      ubuntu16:
        containerImage: ubuntu:16.04
      ubuntu18:
        containerImage: ubuntu:18.04
      ubuntu19:
        containerImage: ubuntu:19.04
      debian9:
        containerImage: debain:9

  container: $[ variables['containerImage'] ]

  steps:
  - script: |
      apt-get install git cmake qtbase5-dev qttools5-dev build-essential libx11-dev libxtst-dev libgl1-mesa-dev libssl-dev libavahi-compat-libdnssd-dev debhelper devscripts
    displayName: 'Install Pakages'


  - script: |
      mkdir build
      cd build
      cmake ..
      make
    displayName: 'Build'
