trigger:
- master

jobs: 
- job: Linux
  pool: 
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      ubuntu16:
        image: symless/ubuntu-sudo:16.04
      ubuntu18:
        image: symless/ubuntu-sudo:18.04
      ubuntu19:
        image: symless/ubuntu-sudo:19.04

  container: $[ variables['image'] ]

  steps:
  - script: |
      sudo ln -snf /usr/share/zoneinfo/Europe/London /etc/localtime
      sudo echo "Europe/London" > /etc/timezone
    displayName: 'Sort out timezones as they are preventing non interactive builds'

  - script: |
      sudo DEBIAN_FRONTEND=noninteractive 
      sudo apt-get -y update
      sudo apt-get -y upgrade
      sudo apt-get -y install git cmake qtbase5-dev qttools5-dev build-essential libx11-dev libxtst-dev libgl1-mesa-dev libssl-dev libavahi-compat-libdnssd-dev debhelper devscripts
    displayName: 'Install Pakages'

  - script: |
      mkdir build
      cd build
      cmake ..
      make
    displayName: 'Build'
