trigger:
- master

jobs: 
- job: LinuxRHEL
  pool: 
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      centos7:
        image: centos:7

  container: $[ variables['image'] ]

  steps:
  - script: |
      sudo yum groupinstall "Development Tools"
      sudo yum -y install epel-release cmake3 boost-static git libXtst-devel qt5-qtbase-devel qt5-qtdeclarative-devel libcurl-devel openssl-devel
    displayName: 'Install Pakages'
    
  - script: |
      mkdir build
      cd build
      cmake ..
      make
    displayName: 'Build'

  