trigger:
- master

jobs: 
- job: Linux
  pool: 
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      ubuntu16:
        image: symless/ubuntu-sudo:16.04
        endpoint: 'docker-hub'
      ubuntu18:
        image: symless/ubuntu-sudo:18.04
        endpoint: 'docker-hub'
      ubuntu19:
        image: symless/ubuntu-sudo:19.04
        endpoint: 'docker-hub'

  container: $[ variables['containerResource'] ]

  steps:
  - script: |
      DEBIAN_FRONTEND=noninteractive sudo apt-get -y upgrade
      sudo apt-get -y install git cmake qtbase5-dev qttools5-dev build-essential libx11-dev libxtst-dev libgl1-mesa-dev libssl-dev libavahi-compat-libdnssd-dev debhelper devscripts
    displayName: 'Install Pakages'

  - script: |
      mkdir build
      cd build
      cmake ..
      make
    displayName: 'Build'
