trigger:
- master

jobs: 
- job: MacOS
  strategy:
    matrix:
      sierra:
        image: macOS-10.13
      mojave:
        image: macOS-10.14

  pool: 
    vmImage: $[ variables['image'] ]

  steps:
  - task: CmdLine@2
    inputs:
      script: 'brew install qt'
    displayName: 'Installing QT'

  - task: CmdLine@2
    inputs:
      script: |
        mkdir build
        cd build 
        cmake -DCMAKE_OSX_DEPLOYMENT_TARGET=10.12 -DCMAKE_OSX_ARCHITECTURES=x86_64 -DCMAKE_BUILD_TYPE=Release -DCMAKE_CONFIGURATION_TYPES=Release ..
    displayName: 'Cmake'

  - task: CmdLine@2
    inputs:
      script: |
        cd build
        make
    displayName: 'Compiling'
