config:
  windows:
    dependencies:
      command: choco install Chocolatey.config -y
      qt:
        version: 6.7
        mirror: https://qt.mirror.constant.com/
        base-dir: ./deps/qt
      ci:
        edit-config: Chocolatey.config
        skip-packages:
          - cmake
          - visualstudio2022buildtools

  mac:
    dependencies:
      command: brew bundle --file=Brewfile
      qt:
        version: 6.7
        mirror: https://qt.mirror.constant.com/
        base-dir: ./deps/qt

  linux:
    debian: &debian
      dependencies:
        command: sudo apt-get update; \
          sudo apt-get install -y \
          cmake \
          make \
          g++ \
          xorg-dev \
          libx11-dev \
          libxtst-dev \
          libssl-dev \
          libglib2.0-dev \
          libgdk-pixbuf-2.0-dev \
          libnotify-dev \
          libxkbfile-dev \
          qt6-base-dev \
          qt6-tools-dev \
          qt6-declarative-dev \
          libgtk-3-dev \
          file

    ubuntu:
      <<: *debian

    fedora: &fedora
      dependencies:
        command: sudo dnf check-update; \
          sudo dnf install -y \
          cmake \
          make \
          gcc-c++ \
          openssl-devel \
          glib2-devel \
          gdk-pixbuf2-devel \
          libXtst-devel \
          libnotify-devel \
          libxkbfile-devel \
          qt6-qtbase-devel \
          qt6-qttools-devel \
          qt6-qtdeclarative \
          gtk3-devel \
          rpm-build

    opensuse-tumbleweed: &opensuse-tumbleweed
      dependencies:
        command: sudo zypper refresh; \
          sudo zypper install -y --force-resolution \
          cmake \
          make \
          gcc-c++ \
          libopenssl-devel \
          glib2-devel \
          gdk-pixbuf-devel \
          libXtst-devel \
          libnotify-devel \
          libxkbfile-devel \
          qt6-base-devel \
          qt6-tools-devel \
          qt6-qtdeclarative \
          gtk3-devel \
          rpm-build

    arch: &arch
      dependencies:
        command: sudo pacman -Syu --noconfirm \
          base-devel \
          cmake \
          gcc \
          openssl \
          glib2 \
          gdk-pixbuf2 \
          libxtst \
          libnotify \
          libxkbfile \
          qt6-base \
          qt6-tools \
          qt6-declarative \
          gtk3

    manjaro:
      <<: *arch
