name: Filter JSON
description: A composite action to filter a JSON file using `jq`

inputs:
  json-file:
    description: "The JSON file to filter"
    required: true

  jq-filter:
    description: "A `jq` filter to run on the JSON"
    required: true

outputs:
  json:
    description: "JSON filtered using `jq`"
    value: ${{ steps.filter.outputs.json }}

runs:
  using: "composite"
  steps:
    - id: filter
      shell: bash
      run: |
        echo "Filtering JSON"
        json_file="${{ inputs.json-file }}"
        json=$(jq '${{ inputs.jq-filter }}' $json_file)

        # Verify valid JSON
        echo "$json" | jq empty
        if [ $? -ne 0 ]; then
          echo "Invalid JSON output" > /dev/stderr
          exit 1
        fi

        echo "json=$(echo $json)" | tee $GITHUB_OUTPUT
