name: "Lint clang"
description: "Lint with Clang formatter"

runs:
  using: "composite"

  steps:
    - name: Install dependencies
      shell: bash
      run: pipx install --global clang_format

    - name: Linting with Clang formatter
      uses: ./.github/actions/lint-error
      with:
        format-command: find src/ -regex '.*\.\(cpp\|hpp\|cc\|cxx\|h\|c\|m\|mm\)' -exec clang-format -style=file --assume-filename=$(pwd)/.clang-format -i {} \;
        format-tool: "clang-format"
