name: Feature request
description: Had an idea how to improve Synergy? Share it with us.
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to help us improve Synergy.

  - type: checkboxes
    id: discussion
    attributes:
      label: Discussion
      description: |
        Have you considered starting a discussion instead of requesting a feature?
      options:
        - label: Yes, and I still want to request a feature
          required: true

  - type: dropdown
    id: user-type
    attributes:
      label: What type of Synergy user are you?
      description: This will help us understand the context of your issue.
      options:
        - Customer
        - Code contributor
        - Community user
      default: 0
    validations:
      required: true

  - type: input
    id: ticket-number
    attributes:
      label: Support ticket number (for customers)
      description: |
        If you have a support ticket number, please enter it here.
        Customers are advised to open a support ticket first: https://symless.com/synergy/contact
        This is for customers only (non-customers please ignore this field).
        Leave this blank if you do not have a support ticket or if you're not a customer.
    validations:
      required: false

  - type: dropdown
    id: product
    attributes:
      label: Product name
      description: Which Synergy product are you using?
      options:
        - Synergy 1
        - Synergy 2
        - Synergy 3
      default: 0
    validations:
      required: true

  - type: checkboxes
    id: os
    attributes:
      label: Operating systems (OS)
      description: Which operating systems (OS) are you using?
      options:
        - label: Windows
        - label: macOS
        - label: Linux or Unix
        - label: Other
    validations:
      required: true

  - type: textarea
    id: os-version
    attributes:
      label: OS versions or Linux distros
      description: |
        Please provide the version number of your operating system (OS).
        If you're using Linux, please provide the name of the distribution.
      placeholder: |
        - Windows 11
        - macOS 15
        - Ubuntu 24.04
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Synergy configuration
      description: |
        Please provide a very brief description of your configuration.
        Let us know the OS of the server/host/primary and the OS of the client/guest/secondary.
        This will help us understand how you're using Synergy.
      placeholder: |
        - Windows 11 server, macOS 15 client
        - Each computer has a single monitor
        - Windows is on the left, macOS is on the right
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: What problem are you trying to solve?
      description: |
        The most important part of problem solving is understanding the problem.
        The more detail you provide, the better we can understand your idea.
        “If I had only one hour to save the world, 
        I would spend fifty-five minutes defining the problem,
        and only five minutes finding the solution.”
        — Albert Einstein
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: What solution do you propose?
      description: |
        Please describe the solution you have in mind.
    validations:
      required: true
