name: "Get version"
description: "Gets the version number from GitHub environment"

runs:
  using: "composite"

  steps:
    - run: |
        echo "DESKFLOW_VERSION=$(git describe --long | sed 's/-/./g;s/v//g'  | grep -o '^[0-9]*.[0-9]*.[0-9]*.[0-9]*')">> $GITHUB_ENV
      shell: bash
