name: "Distribute (macOS)"
description: "Create package and upload"
inputs:
  upload-target:
    description: "Where to upload the package (github or google-drive)"
    default: "github"

runs:
  using: "composite"

  steps:
    # Strip symbols from binaries
    - run: cd build; make install/strip
      shell: bash
