name: "Distribute upload"
description: "Uploads the package from the dist dir to GitHub artifacts or Google Drive"
inputs:
  use_github:
    description: "Whether to upload to GitHub artifacts"

  use_gdrive:
    description: "Whether to upload to Google Drive"

  github-target-filename:
    description: "Filename to upload (GitHub artifacts)"

  gdrive-target-base-dir:
    description: "Base directory to upload (Google Drive)"

  gdrive-secret-key:
    description: "Google Drive secret key"

  gdrive-parent-folder-id:
    description: "Google Drive parent folder ID"

  package-version:
    description: "Package version appended to the Google Drive dir"

runs:
  using: "composite"

  steps:
    - if: ${{ !inputs.use_gdrive == 'true' && !inputs.use_github == 'true' }}
      run: echo "Nothing to do, neither 'use_github' nor 'use_gdrive' is set to 'true'"
      shell: bash

    - if: ${{ inputs.use_gdrive == 'true' && !inputs.package-version }}
      run: |
        echo "Input 'package-version' is required when uploading to Google Drive"
        exit 1
      shell: bash

    - if: ${{ inputs.use_gdrive == 'true' }}
      run: |
        SHORT_VERSION=$(echo "${{ inputs.package-version }}" | cut -d'-' -f1)
        echo "SHORT_VERSION=$SHORT_VERSION" >> $GITHUB_ENV
      shell: bash

    # Upload to GitHub
    - if: ${{ inputs.use_github == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.github-target-filename }}
        path: ./dist
        retention-days: 3

    # Upload to Google Drive
    - if: ${{ inputs.use_gdrive == 'true' }}
      uses: symless/gdrive-upload@target-glob
      with:
        credentials: ${{ inputs.gdrive-secret-key }}
        target: "./dist/*"
        parent_folder_id: ${{ inputs.gdrive-parent-folder-id }}
        child_folder: Packages/${{ inputs.gdrive-target-base-dir }}/${{ env.SHORT_VERSION }}/${{ inputs.package-version }}
