name: "Lint cmake"
description: "Lints cmake file"

runs:
  using: "composite"

  steps:
    - name: Setup Python venv
      uses: ./.github/actions/init-python

    - name: Install dependencies
      shell: bash
      run: |
        source .venv/bin/activate
        pip install pyyaml cmake_format

    - name: Linting with CMake formatter
      uses: ./.github/actions/lint-error
      with:
        format-command: ./scripts/lint_cmake.py -f
        format-tool: "cmake-format"
