name: "Setup Python venv"
description: "Creates and caches a Python virtual environment"

inputs:
  cache:
    description: "Cache Python venv"
    default: true

  setup:
    description: "Setup Python venv"
    default: true

  python-bin:
    description: "Python binary to use"
    default: "python3"

  cache-key:
    description: "Cache key (note: hash is appended)"
    required: true

runs:
  using: "composite"

  steps:
    - name: Cache Python venv
      if: ${{ inputs.cache }}
      uses: actions/cache@v4
      with:
        path: .venv
        key: python_venv-${{ inputs.cache-key }}-${{ hashFiles('scripts/pyproject.toml') }}

    - name: Setup Python venv
      if: ${{ inputs.setup }}
      run: ${{ inputs.python-bin }} -m venv .venv
      shell: bash
