name: Ubuntu

on:
  # release:
  #   types: [created]
  push:
    branches: [master]

jobs:
  upload-to-s3:
    runs-on: ubuntu-latest
    container: symless/synergy-core:${{ matrix.distro }}
    env:
      GIT_COMMIT: ${{ github.sha }}
    strategy:
      matrix:
        include:
          - distro: ubuntu20.04
          - distro: ubuntu21.04
    #          - distro: ubuntu18.04 #Need to install git 2.18+
    #          - distro: ubuntu16.04 #Need to install git 2.18+

    name: ${{ matrix.distro }}

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          curl -sL https://deb.nodesource.com/setup_14.x | bash -
          apt-get install -y nodejs
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          . ./version
          make -j

      - uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_bucket: ${{ secrets.AWS_BUKET }}
          source_dir: ./build/bin
          destination_dir: "./synergy3/latest/${{matrix.distro}}/"