name: Build containers

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * 0"

jobs:
  build-containers:
    name: ${{ matrix.os.name }}
    runs-on: ubuntu-latest
    if: ${{ vars.BUILD_CONTAINERS }}

    strategy:
      matrix:
        os:
          - name: debian-12-amd64
            config-dir: debian
            base-image: debian:12
            platform: amd64

          - name: debian-12-arm64
            config-dir: debian
            base-image: arm64v8/debian:12
            platform: arm64

          - name: fedora-40-amd64
            config-dir: fedora
            base-image: fedora:40
            platform: amd64

          - name: fedora-40-arm64
            config-dir: fedora
            base-image: arm64v8/fedora:40
            platform: arm64

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        if: ${{ matrix.os.platform != 'amd64' }}
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/${{ matrix.os.platform }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./.github/docker/${{ matrix.os.config-dir }}
          file: ./.github/docker/${{ matrix.os.config-dir }}/Dockerfile
          tags: symless/synergy-core:${{ matrix.os.name }}
          build-args: DOCKER_BASE_IMAGE=${{ matrix.os.base-image }}
