name: Build containers

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * 0"

jobs:
  build-containers:
    name: ${{ matrix.os.name }}
    runs-on: ubuntu-latest
    if: ${{ vars.BUILD_CONTAINERS }}

    strategy:
      matrix:
        os:
          - name: debian-12
            platforms: linux/amd64,linux/arm64

          - name: fedora-40
            platforms: linux/amd64,linux/arm64

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./.github/docker/${{ matrix.os.name }}
          file: ./.github/docker/${{ matrix.os.name }}/Dockerfile
          tags: symless/synergy-core:${{ matrix.os.name }}
          platforms: ${{ matrix.os.platform }}
