name: Create release

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - release/**

jobs:
  create-tag:
    if: ${{ vars.CREATE_TAGS }}

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Fetch all tags
          fetch-depth: 0

      - name: Read version file
        run: echo "CURRENT_VERSION=$(cat VERSION)" >> $GITHUB_ENV

      - name: Override stage
        if: ${{ !startsWith(github.ref, 'refs/heads/release') }}
        run: echo "OVERRIDE_STAGE=snapshot" >> $GITHUB_ENV

      - name: Get next version
        id: next-version
        uses: symless/actions/next-version@master
        with:
          current-version: ${{ env.CURRENT_VERSION }}
          override-stage: ${{ env.OVERRIDE_STAGE }}

      - name: Create git tag
        uses: actions/github-script@v7
        with:
          script: |
            const ref = `refs/tags/${{ steps.next-version.outputs.next-version }}`;
            const sha = context.sha;
            await github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: ref,
              sha: sha,
            });
