name: Check if tech support issue
on:
  issues:
    types: [opened]

jobs:
  check-issue-tech-support:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check if issue requires tech support
        id: issue-check
        run: ./scripts/github.py --issue-check-tech-support
        env:
          ISSUE_BODY: ${{ github.event.issue.body }}

      - name: Add comment for customer
        if: steps.issue-check.outputs.may-need-tech-support == 'true'
        env:
          COMMENT_BODY: |
            Hello, as a customer, you're entitled to tech support which is included in your
            license. Please [raise a support ticket](https://symless.com/synergy/contact)
            if you'd like to take advantage of that. If that works for you, then please let
            us know your ticket number so we can continue the discussion there.
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: process.env.COMMENT_BODY
            });
