on: 
  issues:
    types: [ opened ]
    
name: Send Issue to Jira
jobs:
  jiraIssueCreation:
    name: Jira Issue Creation Demo
    runs-on: ubuntu-latest
    
    
    steps:
      - name: Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        
      - name: Create
        id: create          
        uses: atlassian/gajira-create@master
        with:
          project: SYNERGY
          issuetype: Task
          summary: |
            ${{ github.event.issue.title }}
          description: |
            Opened by:  ${{ github.event.issue.user.login }}
            ${{ github.event.issue.body }}
            
      - name: Update issue body
        uses: AsasInnab/pr-body-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          body: |
            Jira Issue: ${{ steps.create.outputs.issue }}
            ${{ github.event.issue.body }}
            
