on: push

jobs:
  ubuntu20:
    runs-on: ubuntu-latest
    container: symless:ubuntu20.04

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        . ./version
        make -j