on: push

jobs:
  build-arch64:
    runs-on: ubuntu-latest
    container: symless/synergy-core:${{ matrix.distro }}
    env:
      GIT_COMMIT: ${{ github.sha }}
    strategy:
      matrix:
        include:
          - distro: ubuntu20.04
          - distro: ubuntu19.10
          - distro: ubuntu18.04

    name: ${{ matrix.distro }}

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        . ./version
        make

    - name: Run unit test
      run: ./build/bin/unittests

  build_armhf:
    runs-on: [self-hosted, armhf]
    env:
      GIT_COMMIT: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          . ./version
          make -j3

      - name: Run unit test
        run: ./build/bin/unittests