name: Ubuntu-flatpak

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-arch64:
    runs-on: ubuntu-latest
    container: symless/synergy-core:ubuntu${{ matrix.distro }}
    env:
      GIT_COMMIT: ${{ github.sha }}
    strategy:
      matrix:
        distro: ['22.04']
        flag: ['-j']

    name: ubuntu-flatpak

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      
      - name: Work around https://github.com/actions/checkout/issues/766
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Install flatpak
        run: |
          sudo apt install flatpak
          flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          flatpak install org.kde.Platform//5.15-21.08
          flatpak install org.kde.Sdk//5.15-21.08

      - name: Build
        run: | 
          cd flatpak
          flatpak-builder build com.symless.Synergy.yml --disable-cache --force-clean
          flatpak build-finish build
          mv com.symless.Synergy.desktop ./build/files/share/applications/com.symless.Synergy.desktop
          flatpak build-export export build
          flatpak build-bundle export synergy.flatpak com.symless.Synergy master --runtime-repo=https://flathub.org/repo/flathub.flatpakrepo