name: Ubuntu-flatpak

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-flatpak-bundle:
    name: ubuntu-flatpak
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name: [synergy, synergy-enterprise, synergy-business]
        include:
          - name: synergy
            remote_folder: v1-core-standard
            enterprise: ""
            business: ""
          - name: synergy-enterprise
            remote_folder: v1-core-enterprise
            enterprise: "1"
            business: ""
          - name: synergy-business
            remote_folder: v1-core-business
            enterprise: ""
            business: "1"
    container:
      image: bilelmoussaoui/flatpak-github-actions:kde-5.15-21.08
      options: --privileged
    env:
      GIT_COMMIT: ${{ github.sha }}
      SYNERGY_ENTERPRISE: ${{ matrix.enterprise }}
      SYNERGY_BUSINESS: ${{ matrix.business }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
        name: "Build"
        with:
          bundle: ${{ matrix.name }}.flatpak
          manifest-path: flatpak/com.symless.Synergy.yml

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        if: "github.event_name == 'pull_request'"
        with:
          name: Bundle
          path: ${{ matrix.name }}.flatpak
          retention-days: 1

      - run: ls -lah

      # - name: Send package to Binary Storage
      #   if: "github.event_name == 'pull_request'"
      #   uses: garygrossgarten/github-action-scp@v0.7.3
      #   with:
      #     local: "${{ github.workspace }}/${{ matrix.name }}.flatpak"
      #     remote: "${{ secrets.BINARIES_SSH_DIR }}/flatpak_builds/"
      #     host: ${{ secrets.BINARIES_SSH_HOST }}
      #     username: ${{ secrets.BINARIES_SSH_USER }}
      #     privateKey: ${{ secrets.BINARIES_SSH_KEY }}
