name: Ubuntu-flatpak

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-arch64:
    runs-on: ubuntu-latest
    env:
      GIT_COMMIT: ${{ github.sha }}

    name: ubuntu-flatpak

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Install flatpak
        run: |
          sudo su
          apt-get update
          echo "Update Done"
          apt-get install flatpak
          echo "Flatpak install Done"
          flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          echo "Flatpak remote add flathub"
          flatpak install org.kde.Platform//5.15-21.08
          echo "Flatpak install Platform done"
          flatpak install org.kde.Sdk//5.15-21.08
          echo "Flatpak install SDK done"
          flatpak install flatpak-builder
          echo "Flatpak install flatpak-builder done"

      - name: Build
        run: | 
          cd flatpak
          flatpak-builder build com.symless.Synergy.yml --disable-cache --force-clean
          flatpak build-finish build
          mv com.symless.Synergy.desktop ./build/files/share/applications/com.symless.Synergy.desktop
          flatpak build-export export build
          flatpak build-bundle export synergy.flatpak com.symless.Synergy master --runtime-repo=https://flathub.org/repo/flathub.flatpakrepo