name: Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test-artifacts:
    runs-on: ubuntu-latest
    container: symless/synergy-core:ubuntu20.04

    env:
      GIT_COMMIT: ${{ github.sha }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Build
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          . ./version
          make -j
          tar -cvf synergy.tar ./bin/*

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: linux-test-artifacts
          path: build/synergy.zip
          retention-days: 1

  test-artifacts:
    runs-on: ubuntu-latest
    needs: build-test-artifacts
    name: ${{ matrix.distro }}
    container: symless/synergy-core:${{ matrix.distro }}
    strategy:
      matrix:
        include:
          - distro: ubuntu20.04
          - distro: ubuntu19.10
          - distro: debian10
          - distro: fedora30
          - distro: fedora29
          - distro: centos8
          # - distro: centos7.6 #Need to install git 2.18+
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v2
      with:
        name: linux-test-artifacts
        path: synergy.zip

    - name: Set execute flag
      run: tar -xcf synergy.tar

    - name: Run unit test
      run: ./bin/unittests
