name: Build Raspberry Pi

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-on-pi:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: [self-hosted, linux, ARM, pi-3]
            name: raspios-pi-3
          - os: [self-hosted, linux, ARM64, pi-4]
            name: raspios-pi-4
    env:
      GIT_COMMIT: ${{ github.sha }}

    steps:
    - uses: actions/checkout@v2

    - name: Build deb
      shell: bash
      run: |
        mkdir -p build-release; cd build-release
        cmake ..
        cd ..
        . ./build-release/version
        SYNERGY_VERSION="$SYNERGY_VERSION_MAJOR.$SYNERGY_VERSION_MINOR.$SYNERGY_VERSION_PATCH"
        SYNERGY_REVISION=`git rev-parse --short=8 HEAD`
        SYNERGY_DEB_VERSION="${SYNERGY_VERSION}.${SYNERGY_VERSION_STAGE}.${SYNERGY_REVISION}"
        dch --create --package "synergy" --controlmaint --distribution unstable --newversion $SYNERGY_DEB_VERSION "Initial release"
        export GPG_TTY=$(tty)
        debuild --preserve-envvar SYNERGY_* --preserve-envvar GIT_COMMIT -us -uc
        mkdir -p standard_package
        cd ..
        filename=$(ls synergy_*${SYNERGY_REVISION}*.deb)
        filename_new="synergy_${SYNERGY_VERSION}-${SYNERGY_VERSION_STAGE}.${SYNERGY_REVISION}_raspios${filename##*${SYNERGY_REVISION}}"
        echo $filename
        echo $filename_new
        ls -la ${{ github.workspace }}
        ls -la ${{ github.workspace }}/standard_package
        mv $filename ${{ github.workspace }}/standard_package/$filename_new
        cd ${{ github.workspace }}/standard_package
        md5sum $filename_new >> ${filename_new}.checksum.txt
        sha1sum $filename_new >> ${filename_new}.checksum.txt
        sha256sum $filename_new >> ${filename_new}.checksum.txt
        ls -la

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.name }}
        path: ./standard_package