name: Ubuntu-flatpak

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  flatpak:
    name: ubuntu-flatpak
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:kde-5.15-21.08
      options: --privileged
    env:
      GIT_COMMIT: ${{ github.sha }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
        name: "Build"
        with:
          bundle: synergy.flatpak
          manifest-path: flatpak/com.symless.Synergy.yml

      - run: ls -lah

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        if: "github.event_name == 'pull_request'"
        with:
          name: Bundle
          path: synergy.flatpak
          retention-days: 1
