# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler/blob/master/README.md

name: "Lint ChangeLog"
on:
  pull_request:

jobs:
  lint-changelog:
    if: ${{ !github.event.pull_request.draft }}

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Get changes
        id: file_changes
        uses: trilom/file-changes-action@v1.2.4
        with:
          output: ","

      - name: Show modified
        run: echo '${{ steps.file_changes.outputs.files_modified}}'

      - name: Check
        run: |
          if [[ "${{ steps.file_changes.outputs.files_modified}}" == *"ChangeLog"* ]]; then
            echo "ChangeLog has been updated"
          else
            echo "::error file=app.js,line=10,col=15::Changelog hasn't been updated"
            exit 1
          fi
