# We use `workflow_run` to securely add a comment to the PR.
# PRs opened by external forks do not have write access to their PR, so can't add comments.
name: PR lint comment

on:
  workflow_run:
    workflows: ["Lint Clang", "Lint CMake"]
    types:
      - completed

jobs:
  lint-comment:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.event == 'pull_request'

    steps:
      # Modified example taken directly from the 'workflow_run' event documentation.
      # It seems that using `actions/download-artifact@v4` with `github.event.workflow_run.id`
      # finds no artifacts (even though this run ID does in fact have artifacts),
      # so we have to use the GitHub API to find the artifact instead.
      - name: Download artifact
        uses: actions/github-script@v6
        with:
          script: |
            let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: context.payload.workflow_run.id,
            });
            let artifact = allArtifacts.data.artifacts[0];
            let download = await github.rest.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: artifact.id,
               archive_format: 'zip',
            });
            let fs = require('fs');
            fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/artifact.zip`, Buffer.from(download.data));

      - name: Unzip artifact
        run: unzip artifact.zip

      - name: Debug
        run: ls -R

      - name: Read diff file
        id: changes
        run: |
          file=$(find . -name '*.diff')
          if [ -z "$file" ]; then
            echo "No changes detected"
            exit 0
          fi

          echo "file=$file" >> $GITHUB_OUTPUT
          {
            echo "diff<<EOF"
            cat $file
            echo "EOF"
          } >> $GITHUB_OUTPUT

      - name: PR comment (lint source hint)
        if: steps.changes.outputs.diff
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: ${{ github.event.workflow_run.name }}
          message: |
            ❌ Lint failed: It looks like your changes don't match our code style.

            🛠️ Please apply this patch with `git apply`:
            ```diff
            ${{ steps.changes.outputs.diff }}
            ```

      - name: Delete PR comment
        if: ${{ !steps.changes.outputs.diff }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: ${{ github.event.workflow_run.name }}
          delete: true
