name: "Valgrind Analysis"

on:
  workflow_dispatch:
  workflow_call:

jobs:
  valgrind-analysis:
    runs-on: ubuntu-latest
    container: deskflow/deskflow:ubuntu-22.04-amd64
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # the fetch-tags option for checkout does not work correctly so we need todo this
      - name: Fetch tags
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
          git fetch --tags --force

      - name: Install dependencies
        run: |
          apt-get update -y
          apt-get install ca-certificates gpg wget -y
          # Deskflow requires at least CMake 3.24
          # This mirrors instructions at https://apt.kitware.com
          wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null \
            | gpg --dearmor - \
            > /usr/share/keyrings/kitware-archive-keyring.gpg
          echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ jammy main' \
            > /etc/apt/sources.list.d/kitware.list
          ./scripts/install_deps.py &&
          apt install valgrind cmake -y
        env:
          # Prevent apt prompting for input.
          DEBIAN_FRONTEND: noninteractive

      - name: Configure
        run: cmake -B build --preset=linux-release

      - name: Build
        run: cmake --build build -j8

      - name: Valgrind unit tests
        id: unittests
        uses: ./.github/actions/run-valgrind
        with:
          executable: ./build/bin/unittests

      - name: Valgrind integration tests
        id: integtests
        uses: ./.github/actions/run-valgrind
        with:
          executable: ./build/bin/integtests

      - name: Set job summary
        run: |
          backticks='```'
          message=$(cat <<EOF
          ## Valgrind summary

          ### Unit tests
          $backticks
          ${{ steps.unittests.outputs.summary }}
          $backticks

          ### Integration tests
          $backticks
          ${{ steps.integtests.outputs.summary }}
          $backticks
          EOF
          )

          echo "$message" >> $GITHUB_STEP_SUMMARY
