name: "Valgrind Analysis"

on:
  workflow_dispatch:
  workflow_call:

jobs:
  valgrind-analysis:
    runs-on: ubuntu-latest
    container: deskflow/deskflow:ubuntu-22.04-amd64
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # the fetch-tags option for checkout does not work correctly so we need todo this
      - name: Fetch tags
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
          git fetch --tags --force

      - name: Add Kitware repo
        uses: ./.github/actions/add-kitware-repo
        with:
          distro: jammy

      - name: Install dependencies
        run: |
          ./scripts/install_deps.py
          apt install valgrind cmake -y
        env:
          # Prevent apt prompting for input.
          DEBIAN_FRONTEND: noninteractive

      - name: Configure
        run: cmake -B build -G "Ninja"

      - name: Build
        run: cmake --build build -j8

      - name: Valgrind unit tests
        id: unittests
        uses: ./.github/actions/run-valgrind
        with:
          executable: ./build/bin/unittests

      - name: Valgrind integration tests
        id: integtests
        uses: ./.github/actions/run-valgrind
        with:
          executable: ./build/bin/integtests

      - name: Set job summary
        run: |
          backticks='```'
          message=$(cat <<EOF
          ## Valgrind summary

          ### Unit tests
          $backticks
          ${{ steps.unittests.outputs.summary }}
          $backticks

          ### Integration tests
          $backticks
          ${{ steps.integtests.outputs.summary }}
          $backticks
          EOF
          )

          echo "$message" >> $GITHUB_STEP_SUMMARY
